# Generated by Django 5.0.7 on 2024-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
    ]
