# Generated by Django 5.0.7 on 2024-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
