# Generated by Django 5.0.7 on 2024-08-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
