# Generated by Django 5.0.7 on 2024-08-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appointment_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_data',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
