# Generated by Django 5.0.7 on 2024-08-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appointment_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_data',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
