# Generated by Django 5.0.7 on 2024-08-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine.provider'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine.service'),
        ),
    ]
