# Generated by Django 5.0.7 on 2024-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_first_name',
            field=models.CharField(default='firstname', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(default='gender', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_last_name',
            field=models.CharField(default='lastname', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_national_id',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone_number',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
