# Generated by Django 5.0.7 on 2024-09-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('medicine', '0002_doctorsmodel_locationmodel_servicemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.doctorsmodel'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.servicemodel'),
        ),
    ]
