# Generated by Django 5.0.7 on 2024-08-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
        ('Medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='provider_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicine.providers'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Medicine.services'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('SCH', 'Scheduled'), ('COM', 'Completed'), ('CAN', 'Canceled')], default='SCH', max_length=3),
        ),
    ]
