# Generated by Django 5.0.7 on 2024-08-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_appointments_provider_id_appointments_service_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointments',
            table='appointments',
        ),
    ]
