# Generated by Django 5.0.7 on 2024-08-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='provider',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
