# Generated by Django 5.0.7 on 2024-08-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_alter_providers_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locations',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='providers',
            table='providers',
        ),
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
