# Generated by Django 5.0.7 on 2024-09-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_provider_alter_appointment_service'),
        ('medicine', '0002_doctorsmodel_locationmodel_servicemodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='doctorsmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.locationmodel'),
        ),
        migrations.AddField(
            model_name='doctorsmodel',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.servicemodel'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
