# Generated by Django 5.0.7 on 2024-09-02 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='stars_average',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
