# Generated by Django 5.0.7 on 2024-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicine', '0002_rename_locations_location_rename_providers_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='speciality',
            field=models.CharField(choices=[('FM', 'Family medicine'), ('IM', 'Internal medicine'), ('EM', 'Emergency medicine'), ('OT', 'Other medicine')], max_length=200),
        ),
    ]
