openapi: 3.0.3
info:
  title: Digital Appointment API
  version: 0.0.0
  description: Accepting and setting appointments for patients
paths:
  /api/accounts/auth/google/callback/:
    get:
      operationId: accounts_auth_google_callback_retrieve
      description: |-
        the get api for authenticate with google way
        and do login if have exist account or signup
        if we have an account in one api
      tags:
      - GoogleAuth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/auth/google/start/:
    post:
      operationId: accounts_auth_google_start_create
      description: |-
        with this api front developer can use
        google authenticate very easy
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/auth/sms/:
    post:
      operationId: accounts_auth_sms_create
      description: generate authentication code for select mobile number
      tags:
      - sms
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sms'
          description: ''
  /api/accounts/login/:
    post:
      operationId: accounts_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTokenObtainPair'
          description: ''
  /api/accounts/login/refresh/:
    post:
      operationId: accounts_login_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/accounts/profile/:
    get:
      operationId: accounts_profile_retrieve
      tags:
      - User
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/accounts/sms/verify:
    post:
      operationId: accounts_sms_verify_create
      description: verify mobile number with code stored in cache
      tags:
      - sms
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sms'
          description: ''
  /api/accounts/user/:
    get:
      operationId: accounts_user_retrieve
      description: save Schema of api for guide other Distributor
      tags:
      - User
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    post:
      operationId: accounts_user_create
      description: save Schema of api for guide other Distributor
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/accounts/user/{id}/:
    get:
      operationId: accounts_user_retrieve_2
      description: save Schema of api for guide other Distributor
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - User
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: accounts_user_update
      description: save Schema of api for guide other Distributor
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: accounts_user_destroy
      description: save Schema of api for guide other Distributor
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - accounts
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/interaction/post_comment/:
    post:
      operationId: interaction_post_comment_create
      description: save patient comment about provider
      tags:
      - Comments
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
          description: ''
  /api/medicine/ProviderDetail/{id}/:
    get:
      operationId: medicine_ProviderDetail_retrieve
      description: Handle GET requests to retrieve provider details along with comments.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - Provider
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
          description: ''
  /api/medicine/Service/:
    get:
      operationId: medicine_Service_retrieve
      tags:
      - Service
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
          description: ''
    post:
      operationId: medicine_Service_create
      tags:
      - medicine
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/medicine/locations/:
    get:
      operationId: medicine_locations_retrieve
      description: get locations for select a provider
      tags:
      - Location
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
          description: ''
    post:
      operationId: medicine_locations_create
      description: |-
        serializer.is_valid(raise_exception=True) this code for
        validate serializer and not different with code in line 43
      tags:
      - medicine
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/medicine/provider/:
    get:
      operationId: medicine_provider_retrieve
      tags:
      - Provider
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
          description: ''
    post:
      operationId: medicine_provider_create
      tags:
      - medicine
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/medicine/speciality/list/:
    get:
      operationId: medicine_speciality_list_retrieve
      tags:
      - Specialty
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Speciality'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Comment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        comment:
          type: string
        stars:
          type: integer
          maximum: 5
          minimum: 1
          nullable: true
        create_date:
          type: string
          format: date-time
          readOnly: true
        update_date:
          type: string
          format: date-time
          readOnly: true
        user:
          type: integer
        provider:
          type: integer
      required:
      - comment
      - create_date
      - id
      - provider
      - update_date
      - user
    CustomTokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - password
      - username
    Location:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        address:
          type: string
        city:
          type: string
          maxLength: 50
        state:
          type: string
          maxLength: 50
        zip_code:
          type: string
          maxLength: 10
        created_date:
          type: string
          format: date-time
          readOnly: true
        updated_date:
          type: string
          format: date-time
          readOnly: true
      required:
      - address
      - city
      - created_date
      - id
      - name
      - state
      - updated_date
      - zip_code
    Provider:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/User'
        location:
          $ref: '#/components/schemas/Location'
        speciality:
          type: string
          maxLength: 255
        stars_average:
          type: integer
          maximum: 5
          minimum: 1
          nullable: true
        created_date:
          type: string
          format: date-time
          readOnly: true
        updated_date:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_date
      - id
      - location
      - speciality
      - updated_date
      - user
    Service:
      type: object
      description: Service model Serializer
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        duration:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        created_date:
          type: string
          format: date-time
          readOnly: true
        updated_date:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_date
      - id
      - name
      - price
      - updated_date
    Sms:
      type: object
      properties:
        mobile:
          type: string
          maxLength: 11
        code:
          type: string
          maxLength: 6
      required:
      - mobile
    Speciality:
      type: object
      properties:
        speciality:
          type: string
          maxLength: 255
      required:
      - speciality
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        password:
          type: string
          writeOnly: true
          maxLength: 128
        last_login:
          type: string
          format: date-time
          nullable: true
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        username:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 200
        phone_number:
          type: string
          maxLength: 20
        birth_data:
          type: string
          format: date-time
          nullable: true
        update_at:
          type: string
          format: date-time
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        expire_at:
          type: string
          format: date-time
          nullable: true
      required:
      - created_at
      - email
      - first_name
      - id
      - last_name
      - password
      - phone_number
      - update_at
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
